version: '3'

services:
### NGINX Server #########################################
    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=php
          - PHP_UPSTREAM_PORT=9000
      volumes:
        - ./www:/var/www:cached
        - ./logs/nginx/:/var/log/nginx
        - ./nginx/sites/:/etc/nginx/sites-available
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - php
    #   networks:
    #     - frontend
    #     - backend    
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        depends_on:
            - postgres
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    ### PostgreSQL ###########################################
    postgres:
        build: ./postgres
        volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
        ports:
        - "${POSTGRES_PORT}:5432"
        environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        # networks:
        #   - backend
### Node #########################################
    node:
        build: ./node
        volumes:
        - ./www:/var/www
        ports:
        - "4321:4321"
        environment:
        - "USER_GID=1001"
        - "USER=1001"
        depends_on: 
        - postgres
        # networks:
        #   - docker_app-network
        # expose:
        #   - "9000"